### ISSUE TITLE
Korean Layout Doesn't work

### ISSUE THREAD

**Issue by VitaJane** [GreyWyvern/virtual-keyboard#4]
Hello, a friend of mine and I happened to fix the issue with the Korean layout not properly creating Korean characters (Hangul). We were wondering if you interested in these changes? 

We also implemented quite a few other changes, like making it easier to select a layout (shows English name, and can be searched), making the keyboard movable, and adding a help button.

I can make a pull request if you're interested. There are a lot of changes, so I wanted to at least ask before just making a pull request.

**Comment by GreyWyvern** [comment]
Hey thanks! Sure, please create a pull request, however since you have a lot of changes, I would prefer if you broke up the updates into discreet PRs for each separate improvement. They may work great for your particular application, but not every change may be within the scope of what I'd like the keyboard to do.

**Comment by VitaJane** [comment]
Thanks, just made a pull request with all the Korean changes specifically. Hopefully it's more manageable, let me know if you have any questions about it. It's still kind of large, just because of how the Korean writing system transfers over to typing.
